### ISSUE TITLE
TML crash

### ISSUE THREAD

**Issue by Fidias350** [ScalarVector1/DragonLens#44]
I got this issue every time I try to Ioad the game with this mod
It seems to be related to the ToolData
[client.log](https://github.com/ScalarVector1/DragonLens/files/10984410/client.log)

**Comment by ScalarVector1** [comment]
Hi, this was fixed in a recent patch. If you still have bad tool data you may need to delete your tool data folder (C:/Users/MyGames/Terraria/TModLoader/DragonLensLayouts/ToolData)Hi, this was fixed in a recent patch. If you still have bad tool data you may need to delete your tool data folder (C:/Users/MyGames/Terraria/TModLoader/DragonLensLayouts/ToolData)

**Comment by ReverseAli** [comment]
uhh i have the same issue too and i just downloaded ther mod

**Comment by ReverseAli** [comment]
[client.log](https://github.com/ScalarVector1/DragonLens/files/10985435/client.log)
this it

**Comment by Fidias350** [comment]
For some reason the problem still persists
I delete the old ToolData, I reload the mod, and it still creates a bad ToolData which crashes my game

**Comment by ReverseAli** [comment]
same

**Comment by ScalarVector1** [comment]
Your log indicates you are not on the latest version of the mod. The latest version is 1.3.0, not 1.2.2
